name: adamctl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./cmd
        env:
          TZ: America/Los_Angeles

      - name: Build artifacts
        run: >
          GOOS=darwin GOARCH=amd64 go build -v -o build/adamctl-darwin-amd64 . &&
          GOOS=darwin GOARCH=arm64 go build -v -o build/adamctl-darwin-arm64 . &&
          GOOS=linux GOARCH=amd64 go build -v -o build/adamctl-linux-amd64 . &&
          GOOS=linux GOARCH=arm64 go build -v -o build/adamctl-linux-arm64 .
