name: adamctl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        id: build
        run: go build -v .

      - name: Test
        id: test
        run: go test -v ./cmd
        env:
          TZ: America/Los_Angeles

      - name: Build artifacts
        id: build_artifacts
        if: ${{ github.ref_name == 'main' }}
        run: |
          GOOS=darwin GOARCH=amd64 go build -o build/adamctl-darwin-amd64 . &&
          GOOS=darwin GOARCH=arm64 go build -o build/adamctl-darwin-arm64 . &&
          GOOS=linux GOARCH=amd64 go build -o build/adamctl-linux-amd64 . &&
          GOOS=linux GOARCH=arm64 go build -o build/adamctl-linux-arm64 .

      - name: Release
        id: release
        run: |
          SHA="${{ github.sha }}"
          VERSION=${SHA:0:8}
          TAG=v-$VERSION
          git tag "$TAG"
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}