name: adamctl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        id: build
        run: go build -v .

      - name: Test
        id: test
        run: go test -v ./cmd
        env:
          TZ: America/Los_Angeles

      - name: Build artifacts
        id: build_artifacts
        if: ${{ github.ref_name == 'main' }}
        run: >
          GOOS=darwin GOARCH=amd64 go build -o build/adamctl-darwin-amd64 . &&
          GOOS=darwin GOARCH=arm64 go build -o build/adamctl-darwin-arm64 . &&
          GOOS=linux GOARCH=amd64 go build -o build/adamctl-linux-amd64 . &&
          GOOS=linux GOARCH=arm64 go build -o build/adamctl-linux-arm64 .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Upload release artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          if-no-files-found: error
          path: output/**/*
