name: adamctl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Build
        id: build
        run: go build -v .

      - name: Test
        id: test
        run: go test -v ./cmd
        env:
          TZ: America/Los_Angeles

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        id: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.6'

      - name: Build artifacts
        id: build_artifacts
        run: |
          GOOS=darwin GOARCH=amd64 go build -o build/adamctl-darwin-amd64 . &&
          GOOS=darwin GOARCH=arm64 go build -o build/adamctl-darwin-arm64 . &&
          GOOS=linux GOARCH=amd64 go build -o build/adamctl-linux-amd64 . &&
          GOOS=linux GOARCH=arm64 go build -o build/adamctl-linux-arm64 .

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Release
        id: create-release
        run: |
          TAG="${{ steps.tag_version.outputs.new_tag }}"
          gh release create "$TAG" --generate-notes
          gh release upload "$TAG" build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
